name: Build Pipeline

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: write
  actions: read
  
jobs:
  build:
    runs-on: self-hosted
    environment: DEV

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          
      - name: install ADF Utilities package
        run: npm install
        working-directory: ${{github.workspace}}/
      
        
      - name: Validate
        run: npm run build validate ${{github.workspace}}/ /subscriptions/0d3ce63c-abaa-48ae-bbe1-f582cea576b9/resourceGroups/mayurr-rg/providers/Microsoft.DataFactory/factories/mayurr-adf-dev
        working-directory: ${{github.workspace}}/
        
      - name: Validate and Generate ARM template
        run: npm run build export ${{github.workspace}}/ /subscriptions/0d3ce63c-abaa-48ae-bbe1-f582cea576b9/resourceGroups/mayurr-rg/providers/Microsoft.DataFactory/factories/mayurr-adf-dev "ExportedArmTemplate"
        working-directory: ${{github.workspace}}/
        
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # find ${{github.workspace}}/ -name "*.json" -o -name "*.ps1" | while read file; do git add "$file"; done
          git add ExportedArmTemplate/
          git commit -m "Update ARM templates [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExportedArmTemplate 
          path: ${{github.workspace}}/ExportedArmTemplate  
  
