name: Release

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-24.04
    environment: DEV
    steps:

      # - name: Download a Build Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: ExportedArmTemplate

      - name: Checkout the repository
        uses: actions/checkout@v3
      
      # - name: Copy the artifact
      #   run: |
      #     cp -r ExportedArmTemplate/ ${{ github.workspace }}/ExportedArmTemplate
          
      - name: Login via Az module
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # - name: Read parameters from JSON file and pass to additionalParameters
      #   id: read-params
      #   run: |
      #     additional_params=$(jq -c . /parameters.json)
      #     echo "additionalParams=$additional_params" >> $GITHUB_ENV

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: Mayurr-rg
          dataFactoryName: mayurr-prod-adf
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
          additionalParameters: 'AzureBlobStorage1_properties_typeProperties_connectionString_secretName=prod-sa-cs AzureKeyVault1_properties_typeProperties_baseUrl=https://prodadfkvmayurr.vault.azure.net/'
