name: List Directory Contents

on:
  workflow_dispatch:

jobs:
  list_contents:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List directory contents
        run: ls -la
